// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBazTC6wmOzC1GnG6yFj5zBlx12o46MTkM',
    appId: '1:1015472509991:web:a7f77b738b2eb948432a02',
    messagingSenderId: '1015472509991',
    projectId: 'ecommerce-fc421',
    authDomain: 'ecommerce-fc421.firebaseapp.com',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
    measurementId: 'G-J9D848THC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYIKkQt7QUT_laV-pHOwLd15Ohhx48vQ',
    appId: '1:1015472509991:android:0d699a6337975b94432a02',
    messagingSenderId: '1015472509991',
    projectId: 'ecommerce-fc421',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShklLEui9EC7RujEidNJi1LbBW2ZGzzM',
    appId: '1:1015472509991:ios:9c49f7778204745c432a02',
    messagingSenderId: '1015472509991',
    projectId: 'ecommerce-fc421',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
    androidClientId: '1015472509991-3olr7be3n4btmosl11nr0sq0crt5vqe3.apps.googleusercontent.com',
    iosClientId: '1015472509991-buvc9r9c26ub30g9q85uqrj7pglnlksn.apps.googleusercontent.com',
    iosBundleId: 'com.mobijunction.app',
  );

}
//com.MobiJunction.ecommerce